### ISSUE TITLE
thinkfan exits with failure on sleep-wakeup cycle [systemd,thinkpad]

### ISSUE THREAD

**Issue by bymoz089** [vmatare/thinkfan#125] opened 2021-02-08 23:08 UTC
thinkfan 1.2.1 started via systemd
on Sleep - Wakeup cycle, thinkfan exits with: 
    
    ERROR: Lost sensor read_temps: Failed to read temperature(s) from /sys/class/hwmon/hwmon3/temp1_input: No such device or address

Following entry in config file causes this behavior:

    sensors:
      - hwmon: /sys/class/hwmon
        name: thinkpad
        indices: [1]

Thinkfan seems to exit before thinkfan-wakeup.service gets executed, because thinkfan-wakeup.service always fails on execute.

Excerpt from log:

    Temperatures(bias): 45(0) -> level 0
    Going to sleep: Will allow sensor read errors for the next 2 loops.
    ERROR: Lost sensor read_temps: Failed to read temperature(s) from /sys/class/hwmon/hwmon3/temp1_input: No such device or address
    $

**Comment by ratcashdev** [comment] 2021-03-22 16:47
duplicate of #111

**Closed** 2021-04-15 18:32 UTC
