### ISSUE TITLE
Arch Linux: error while loading shared libraries after yaml-cpp 0.8.0 upgrade

### ISSUE THREAD

**Issue by k1gen** [vmatare/thinkfan#233] opened 2023-09-17 12:37 UTC
yaml-cpp updated to 0.8.0 on arch, so thinkfan stopped working:
`/usr/bin/thinkfan: error while loading shared libraries: libyaml-cpp.so.0.7: cannot open shared object file: No such file or directory`

**Comment by nozwock** [comment] 2023-09-17 13:00
Have you tried the `main` build of thinkfan? Does it also have the incompatibility?

**Comment by nozwock** [comment] 2023-09-17 13:02
You may also try symlinking the `0.8.0` `libyaml` to `libyaml-cpp.so.0.7`, would probably work.

**Comment by k1gen** [comment] 2023-09-17 13:13
haven't tried the `main` build yet, am using v1.3.1 from arch repos. also, while the lib symlink is an ugly decision, it works. `sudo ln -s libyaml-cpp.so.0.8 /usr/lib/libyaml-cpp.so.0.7` fixed the issue for me. waiting for the upstream fix anyway

**Comment by nozwock** [comment] 2023-09-17 13:40
Ok, so all you have to do is rebuild the binary with the updated dependencies.
```
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Checking for module 'systemd'
--   Found systemd, version 254
-- Checking for module 'openrc'
--   Package 'openrc', required by 'virtual:world', not found
-- Checking for module 'yaml-cpp'
--   Found yaml-cpp, version 0.8.0
-- Checking for module 'libatasmart'
--   Found libatasmart, version 0.19
-- Configuring done (0.6s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/thinkfan
```
So you either need to do the lib symlinking or have to rebuild the binary.

**Comment by bssb** [comment] 2023-09-17 17:26
This is pretty much a duplicate of #74, #162, #169.

It's just the way AUR packaging works. If your AUR helper program doesn't automatically rebuild a package when one of its dependency is updated, you have to rebuild the package manually. I don't know of any AUR helpers that can do that btw, I've always rebuilt manually.

**Comment by JohnnyNich** [comment] 2023-10-05 02:08
In this case I've found that even with a yay cleanbuild (recommended solution in the issue #169 ) I receive the same error. Is it required to uninstall an AUR version of Thinkfan and then build it manually from source?

**Closed** 2024-10-15 17:35 UTC
Labels: invalid
