### ISSUE TITLE
Could not find a hwmon with this name: thinkpad

### ISSUE THREAD

**Issue by k1gen** [vmatare/thinkfan#235] opened 2023-12-04 02:03 UTC
```
❯ uname -a
Linux think 6.5.13-hardened1-1-hardened #1 SMP PREEMPT_DYNAMIC Wed, 29 Nov 2023 19:48:03 +0000 x86_64 GNU/Linux
❯ systemctl --no-pager -l status thinkfan
× thinkfan.service - simple and lightweight fan control program
     Loaded: loaded (/usr/lib/systemd/system/thinkfan.service; enabled; preset: disabled)
    Drop-In: /etc/systemd/system/thinkfan.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Mon 2023-12-04 02:57:38 CET; 1min 13s ago
    Process: 557 ExecStart=/usr/bin/thinkfan $THINKFAN_ARGS (code=exited, status=1/FAILURE)
        CPU: 9ms

Dec 04 02:57:38 think systemd[1]: Starting simple and lightweight fan control program...
Dec 04 02:57:38 think thinkfan[557]: ERROR: /etc/thinkfan.conf:3:
                                         name: thinkpad
                                               ^
                                     Could not find a hwmon with this name.
Dec 04 02:57:38 think systemd[1]: thinkfan.service: Control process exited, code=exited, status=1/FAILURE
Dec 04 02:57:38 think systemd[1]: thinkfan.service: Failed with result 'exit-code'.
Dec 04 02:57:38 think systemd[1]: Failed to start simple and lightweight fan control program.
❯ sudo journalctl -b | curl -F'file=@-' https://0x0.st
[sudo] password for olk: 
https://0x0.st/HxEX.txt
```

**Comment by m4tx** [comment] 2024-04-17 20:44
Seems to be duplicate of #118

**Closed** 2024-04-21 10:44 UTC
